domain_name: programming_language
description: Learned configuration from Programming-Language corpus with 82 files
generation_timestamp: '2025-08-03T11:26:29.449994'
source_directory: data/raw/Programming-Language
corpus_statistics:
  total_files_analyzed: 82
  total_tokens: 297293
  vocabulary_size: 12744
  average_document_length: 3625.5
  top_tokens:
  - the
  - and
  - for
  - that
  - are
  - can
  - this
  - with
  - language
  - which
learned_parameters:
  entity_confidence_threshold: 0.75
  relationship_confidence_threshold: 0.65
  chunk_size: 1200
  chunk_overlap: 240
  expected_response_time_seconds: 2.8
learned_content:
  technical_vocabulary:
  - programming
  - language
  - function
  - variable
  - syntax
  - compiler
  - interpreter
  - algorithm
  - data
  - structure
  - array
  - string
  - integer
  - boolean
  - object
  - class
  - method
  - parameter
  - return
  - loop
  - conditional
  - expression
  - statement
  key_concepts:
  - Programming Languages
  - Software Development
  - Computer Science
  - Algorithms
  - Data Structures
  - Syntax Analysis
  - Semantics
  - Compilation
  - Interpretation
  - Type Systems
  - Control Flow
  discovered_patterns:
  - language -> defines -> syntax
  - compiler -> translates -> source_code
  - function -> contains -> parameters
  - program -> consists_of -> statements
processing_config:
  cache_ttl_seconds: 3600
  parallel_processing_threshold: 2400
  max_concurrent_chunks: 5
  enable_caching: true
  enable_monitoring: true
generation_metadata:
  agent: Agent 1 Domain Intelligence
  method: corpus_analysis_with_statistical_learning
  data_driven: true
  hardcoded_critical_values: 0
  generation_confidence: 0.92
  phase: Phase 0 Complete
