repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # DISABLED AUTO-FIXING HOOKS - Manual fixes required
      # - id: trailing-whitespace  # DISABLED: Auto-removes trailing whitespace
      # - id: end-of-file-fixer    # DISABLED: Auto-adds final newlines
      - id: check-yaml              # KEEPS: Only validates YAML syntax
      - id: check-added-large-files # KEEPS: Only checks file sizes
      - id: check-merge-conflict    # KEEPS: Only detects merge conflicts
      - id: debug-statements        # KEEPS: Only detects debug statements

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        files: ^(agents|api|infrastructure|config)/.*\.py$
        args: ["--check", "--diff"]  # CHECK-ONLY MODE: Report issues without auto-fixing

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(agents|api|infrastructure|config)/.*\.py$
        args: ["--profile", "black", "--check-only", "--diff"]  # CHECK-ONLY MODE: Report issues without auto-fixing

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: ^(agents|api|infrastructure|config)/.*\.py$
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        files: ^(agents|api|infrastructure|config)/.*\.py$
        args: ["--ignore-missing-imports"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.47.0
    hooks:
      - id: eslint
        files: ^frontend/.*\.(ts|tsx|js|jsx)$
        additional_dependencies:
          - eslint@8.47.0
          - "@typescript-eslint/eslint-plugin@6.4.1"
          - "@typescript-eslint/parser@6.4.1"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: ^frontend/.*\.(ts|tsx|js|jsx|json|css|md)$
        args: ["--check"]  # CHECK-ONLY MODE: Report issues without auto-fixing

  - repo: local
    hooks:
      # Removed: check-directory-structure (script not found)
      # - id: check-directory-structure

      # Removed: check-hardcoded-values hook (functionality integrated into domain-bias check)
      # The anti-hardcoding functionality is now handled by the domain-bias-check hook below

      - id: prevent-large-artifacts
        name: Prevent large ML artifacts
        entry: bash -c 'find . -name "*.pth" -o -name "*.pkl" -o -name "*.h5" -o -name "*.onnx" | grep -v "\.venv" | grep -v "/venv/" | head -1 | grep -q . && echo "❌ Large ML artifacts detected. Use .gitignore" && exit 1 || exit 0'
        language: system
        pass_filenames: false

      - id: check-venv-not-committed
        name: Ensure venv not in git
        entry: bash -c 'find . -name "venv" -type d | head -1 | grep -q . && echo "❌ Virtual environment detected in git. Add to .gitignore" && exit 1 || exit 0'
        language: system
        pass_filenames: false

      - id: check-domain-bias
        name: Prevent hardcoded domain bias violations
        entry: scripts/hooks/pre-commit-domain-bias-check.sh
        language: system
        files: ^(agents|config|scripts|infrastructure)/.*\.py$
        pass_filenames: false
        description: Enforce Universal RAG zero-domain-bias philosophy - detects hardcoded domain assumptions, predetermined categories, and non-universal patterns
