repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml              # Core: validates YAML syntax
      - id: check-added-large-files # Core: checks file sizes
      - id: check-merge-conflict    # Core: detects merge conflicts

  - repo: local
    hooks:
      # Removed: check-directory-structure (script not found)
      # - id: check-directory-structure

      # Removed: check-hardcoded-values hook (functionality integrated into domain-bias check)
      # The anti-hardcoding functionality is now handled by the domain-bias-check hook below

      - id: prevent-large-artifacts
        name: Prevent large ML artifacts
        entry: bash -c 'find . -name "*.pth" -o -name "*.pkl" -o -name "*.h5" -o -name "*.onnx" | grep -v "\.venv" | grep -v "/venv/" | head -1 | grep -q . && echo "❌ Large ML artifacts detected. Use .gitignore" && exit 1 || exit 0'
        language: system
        pass_filenames: false

      - id: check-venv-not-committed
        name: Ensure venv not in git
        entry: bash -c 'find . -name "venv" -type d -not -path "./.venv/*" | head -1 | grep -q . && echo "❌ Virtual environment detected in git. Add to .gitignore" && exit 1 || exit 0'
        language: system
        pass_filenames: false

      - id: check-domain-bias
        name: Prevent hardcoded domain bias violations
        entry: scripts/hooks/pre-commit-domain-bias-check.sh
        language: system
        files: ^(agents|config|scripts|infrastructure)/.*\.py$
        pass_filenames: false
        description: Enforce Universal RAG zero-domain-bias philosophy - detects hardcoded domain assumptions, predetermined categories, and non-universal patterns
