name: gnn-inference
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytorch=1.13.0
  - torchvision
  - torchaudio
  - pip
  - pip:
    - torch-geometric>=2.2.0
    - numpy>=1.21.0
    - scikit-learn>=1.0.0
    - azure-ml-api