name: Domain Bias Validation

on: [push, pull_request]

jobs:
  validate-zero-domain-bias:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for Domain Bias Violations
        run: |
          ./scripts/hooks/pre-commit-domain-bias-check.sh