name: MaintIE RAG CD

on:
  workflow_run:
    workflows: ["MaintIE RAG CI"]
    types:
      - completed

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps (Staging)
        run: |
          echo "Deploying to staging environment..."
          az containerapp update \
            --name ca-backend-maintie-rag-staging \
            --resource-group rg-maintie-rag-staging \
            --image ${{ secrets.AZURE_REGISTRY_URL }}/maintie-rag-backend:${{ github.sha }} \
            --set-env-vars ENVIRONMENT=staging
        continue-on-error: true

      - name: Run staging health checks
        run: |
          echo "Running staging health checks..."
          sleep 30  # Wait for deployment
          curl -f ${{ secrets.STAGING_BACKEND_URL }}/api/v1/health || echo "Health check failed"

  deploy-production:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps (Production)
        run: |
          echo "Deploying to production environment..."
          az containerapp update \
            --name ca-backend-maintie-rag-production \
            --resource-group rg-maintie-rag-production \
            --image ${{ secrets.AZURE_REGISTRY_URL }}/maintie-rag-backend:${{ github.sha }} \
            --set-env-vars ENVIRONMENT=production
        continue-on-error: true

      - name: Run production health checks
        run: |
          echo "Running production health checks..."
          sleep 60  # Wait longer for production deployment
          curl -f ${{ secrets.PRODUCTION_BACKEND_URL }}/api/v1/health || echo "Health check failed"

      - name: Notify deployment success
        run: |
          echo "Production deployment completed successfully"
          echo "Backend URL: ${{ secrets.PRODUCTION_BACKEND_URL }}"