name: MaintIE RAG CI

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop, feature/** ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
      OPENAI_API_VERSION: ${{ secrets.OPENAI_API_VERSION }}
      OPENAI_DEPLOYMENT_NAME: ${{ secrets.OPENAI_DEPLOYMENT_NAME }}
      OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
      EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
      EMBEDDING_DEPLOYMENT_NAME: ${{ secrets.EMBEDDING_DEPLOYMENT_NAME }}
      EMBEDDING_API_BASE: ${{ secrets.EMBEDDING_API_BASE }}
      EMBEDDING_API_VERSION: ${{ secrets.EMBEDDING_API_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov requests pytest-timeout pytest-asyncio
          pip list

      - name: Debug environment
        run: |
          echo "Python version: $(python --version)"
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Tests directory:"
          ls -la tests/ || echo "No tests directory found"
          echo "Environment variables:"
          env | grep -E "(OPENAI|PYTHON)" || echo "No relevant env vars found"

      - name: Set test environment variables
        run: |
          # Set default values for testing if secrets are not available
          export OPENAI_API_VERSION=${OPENAI_API_VERSION:-"2025-03-01-preview"}
          export OPENAI_MODEL=${OPENAI_MODEL:-"gpt-4.1"}
          export EMBEDDING_MODEL=${EMBEDDING_MODEL:-"text-embedding-ada-002"}
          export EMBEDDING_API_BASE=${EMBEDDING_API_BASE:-"https://clu-project-foundry-instance.openai.azure.com/"}
          export EMBEDDING_API_VERSION=${EMBEDDING_API_VERSION:-"2025-03-01-preview"}
          echo "Test environment variables set"

      - name: Run syntax checks
        run: |
          python -m py_compile api/main.py
          python -m py_compile api/dependencies.py
          echo "Basic syntax check passed"

      - name: Run unit tests
        run: |
          PYTHONPATH=. pytest tests/unit/ -v --tb=short --timeout=300
        timeout-minutes: 10
        continue-on-error: false

      - name: Run integration tests (without Azure credentials)
        run: |
          PYTHONPATH=. pytest tests/integration/test_imports.py tests/integration/test_syntax.py -v --tb=short --timeout=300
        timeout-minutes: 10
        continue-on-error: true

      - name: Check backend structure
        run: |
          echo "Backend directory structure:"
          ls -la
          echo "Services directory:"
          ls -la services/ || echo "No services directory found"
          echo "Core directory:"
          ls -la core/ || echo "No core directory found"
          echo "API directory:"
          ls -la api/ || echo "No api directory found"